# Generated by Django 3.2.4 on 2021-08-12 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('Facebook Likes', 'Facebook Likes'), ('Facebook Follows', 'Facebook Follows'), ('Instagram Likes', 'Instagram Likes'), ('Instagram Follows', 'Instagram Follows'), ('Youtube Likes', 'Youtube Likes'), ('Youtube Views', 'Youtube Views')], max_length=20)),
                ('Quantity', models.CharField(choices=[('50', '50'), ('100', '100'), ('300', '300'), ('500', '500'), ('700', '700'), ('1000', '1000')], max_length=20)),
                ('id_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=20, unique=True)),
                ('img', models.ImageField(upload_to='transactions')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Process', 'In Process'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
