# Generated by Django 3.2.4 on 2021-08-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
