# Generated by Django 3.2.4 on 2021-08-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210813_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
