# Generated by Django 3.2.4 on 2021-08-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_order_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.ImageField(upload_to='transactions/%Y/%m/%d'),
        ),
    ]
