# Generated by Django 3.2.4 on 2021-08-26 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.ImageField(upload_to='transactions/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='ContestEntries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('whatsapp', models.ImageField(upload_to='whatsapp')),
                ('facebook', models.ImageField(upload_to='facebook')),
                ('twitter', models.ImageField(upload_to='twitter')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
