# Generated by Django 3.2.4 on 2021-09-08 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_assignorder_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskQuestions',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateWeeklyContest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='contest')),
                ('title', models.CharField(max_length=50)),
                ('alert', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RobotConfirmationViews',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_code', models.CharField(max_length=50)),
                ('submit_at', models.DateTimeField(auto_now_add=True)),
                ('champ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hero_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.assignorder')),
            ],
        ),
    ]
